#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""aws-telephony-bot - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Deepgram on SageMaker (Speech-to-Text)
- Aws_Bedrock (LLM)
- Deepgram on SageMaker (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""


from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.transports.base_transport import BaseTransport
from pipecat.pipeline.pipeline import Pipeline
import os
from pipecat.transports.daily.transport import DailyParams, DailyTransport
from pipecat.pipeline.task import PipelineParams, PipelineTask
from server_utils import AgentRequest, DialoutSettings
from pipecat.services.aws.llm import AWSBedrockLLMService
from pipecat.services.deepgram.sagemaker.stt import DeepgramSageMakerSTTService
from typing import Any, Optional
from pipecat.services.deepgram.sagemaker.tts import DeepgramSageMakerTTSService
from pipecat.services.deepgram.tts import DeepgramTTSService
from pipecat.runner.types import DailyRunnerArguments, RunnerArguments
from dotenv import load_dotenv
from pipecat.pipeline.runner import PipelineRunner
from loguru import logger
from pipecat.processors.aggregators.llm_response_universal import LLMContextAggregatorPair, LLMUserAggregatorParams
from pipecat.processors.aggregators.llm_response_universal import AssistantTurnStoppedMessage, UserTurnStoppedMessage
from pipecat.processors.logger import FrameLogger
from pipecat.frames.frames import LLMRunFrame
from pipecat.audio.vad.silero import SileroVADAnalyzer

load_dotenv(override=True)




class DialoutManager:
    """Manages dialout attempts with retry logic.

    Handles the complexity of initiating outbound calls with automatic retry
    on failure, up to a configurable maximum number of attempts.

    Args:
        transport: The Daily transport instance for making the dialout
        dialout_settings: Settings containing phone number and optional caller ID        max_retries: Maximum number of dialout attempts (default: 5)
    """

    def __init__(
        self,
        transport: BaseTransport,
        dialout_settings: DialoutSettings,
        max_retries: Optional[int] = 5,
    ):
        self._transport = transport
        self._phone_number = dialout_settings.phone_number
        self._max_retries = max_retries
        self._attempt_count = 0
        self._is_successful = False

    async def attempt_dialout(self) -> bool:
        """Attempt to start a dialout call.

        Initiates an outbound call if retry limit hasn't been reached and
        no successful connection has been made yet.

        Returns:
            True if dialout attempt was initiated, False if max retries reached
            or call already successful
        """
        if self._attempt_count >= self._max_retries:
            logger.error(
                f"Maximum retry attempts ({self._max_retries}) reached. Giving up on dialout."
            )
            return False

        if self._is_successful:
            logger.debug("Dialout already successful, skipping attempt")
            return False

        self._attempt_count += 1
        logger.info(
            f"Attempting dialout (attempt {self._attempt_count}/{self._max_retries}) to: {self._phone_number}"
        )

        await self._transport.start_dialout({"phoneNumber": self._phone_number})
        return True

    def mark_successful(self):
        """Mark the dialout as successful to prevent further retry attempts."""
        self._is_successful = True

    def should_retry(self) -> bool:
        """Check if another dialout attempt should be made.

        Returns:
            True if retry limit not reached and call not yet successful
        """
        return self._attempt_count < self._max_retries and not self._is_successful


async def run_bot(
    transport: BaseTransport, dialout_settings: DialoutSettings | None = None
) -> None:
    """Run the voice bot.

    Sets up the bot pipeline with STT, LLM, and TTS services. If dialout_settings
    is provided, initiates an outbound call with retry logic. Otherwise, waits for
    a participant to join the Daily room directly (e.g. via browser).

    Args:
        transport: Daily transport for the call
        dialout_settings: Phone number and optional caller ID for the outbound call.
            If None, no dialout is performed.
    """
    logger.info("Starting bot")

    # Speech-to-Text service (Deepgram on SageMaker)
    stt = DeepgramSageMakerSTTService(
        endpoint_name=os.getenv("SAGEMAKER_STT_ENDPOINT_NAME"),
        region=os.getenv("AWS_REGION", "us-east-1"),
        settings=DeepgramSageMakerSTTService.Settings(
            model="nova-3",
            language="multi",
            interim_results=True,
            punctuate=True,
            smart_format=False,
        ),
    )

    # Text-to-Speech service (Deepgram on SageMaker)
    tts = DeepgramSageMakerTTSService(
        endpoint_name=os.getenv("SAGEMAKER_TTS_ENDPOINT_NAME"),
        region=os.getenv("AWS_REGION", "us-east-1"),
        settings=DeepgramSageMakerTTSService.Settings(
            voice=os.getenv("DEEPGRAM_VOICE_ID", "aura-2-helena-en"),
        ),
    )

    tts = DeepgramTTSService(api_key=os.getenv("DEEPGRAM_API_KEY"), voice="aura-2-andromeda-en")

    # LLM service
    llm = AWSBedrockLLMService(
        aws_region=os.getenv("AWS_REGION"),
        settings=AWSBedrockLLMService.Settings(
            model=os.getenv("AWS_BEDROCK_MODEL"),
            system_instruction="You are a friendly AI assistant. Respond naturally and keep your answers conversational.",
            temperature=0.8
        ),
    )



    context = LLMContext()
    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(
            vad_analyzer=SileroVADAnalyzer(),
        ),
    )


    
    fl = FrameLogger("out of LLM")


    # Pipeline - assembled from reusable components
    pipeline = Pipeline([
        transport.input(),

        stt,

        user_aggregator,

        llm,
        fl,

        tts,

        
        transport.output(),

        
        assistant_aggregator,

    ])


    task = PipelineTask(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
            audio_in_sample_rate=8000,
            audio_out_sample_rate=8000,
        ),
    )

    if dialout_settings:
        # Dialout mode: call a phone number with retry logic
        dialout_manager = DialoutManager(transport, dialout_settings)

        @transport.event_handler("on_joined")
        async def on_joined(transport, data):
            await dialout_manager.attempt_dialout()

        @transport.event_handler("on_dialout_answered")
        async def on_dialout_answered(transport, data):
            logger.debug(f"Dial-out answered: {data}")
            dialout_manager.mark_successful()

        @transport.event_handler("on_dialout_error")
        async def on_dialout_error(transport, data: Any):
            logger.error(f"Dial-out error, retrying: {data}")

            if dialout_manager.should_retry():
                await dialout_manager.attempt_dialout()
            else:
                logger.error(f"No more retries allowed, stopping bot.")
                await task.cancel()

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info(f"Client disconnected")
        await task.cancel()


    @user_aggregator.event_handler("on_user_turn_stopped")
    async def on_user_turn_stopped(aggregator, strategy, message: UserTurnStoppedMessage):
        timestamp = f"[{message.timestamp}] " if message.timestamp else ""
        line = f"{timestamp}user: {message.content}"
        logger.info(f"Transcript: {line}")

    @assistant_aggregator.event_handler("on_assistant_turn_stopped")
    async def on_assistant_turn_stopped(aggregator, message: AssistantTurnStoppedMessage):
        timestamp = f"[{message.timestamp}] " if message.timestamp else ""
        line = f"{timestamp}assistant: {message.content}"
        logger.info(f"Transcript: {line}")



    runner = PipelineRunner(handle_sigint=False)

    await runner.run(task)


async def bot(runner_args: RunnerArguments):
    """Main bot entry point.

    Supports two modes:
    - Server mode (uv run bot.py -t daily): receives room_url, token, and
      dialout_settings via runner_args.body from the webhook server.
    - Direct mode (uv run bot.py -d): creates a Daily room and waits for a
      participant to join via browser. No dialout is performed.
    """
    # Krisp is available when deployed to Pipecat Cloud
    if os.environ.get("ENV") != "local":
        from pipecat.audio.filters.krisp_viva_filter import KrispVivaFilter

        krisp_filter = KrispVivaFilter()
    else:
        krisp_filter = None

    try:
        if isinstance(runner_args, DailyRunnerArguments) and not runner_args.body:
            # Direct mode: room_url/token come from the runner, no dialout
            room_url = runner_args.room_url
            token = runner_args.token
            dialout_settings = None
        else:
            # Server mode: everything comes from the request body
            request = AgentRequest.model_validate(runner_args.body)
            room_url = request.room_url
            token = request.token
            dialout_settings = request.dialout_settings

        transport = DailyTransport(
            room_url,
            token,
            "Daily PSTN Bot",
            params=DailyParams(
                api_key=os.getenv("DAILY_API_KEY"),
                audio_in_enabled=True,
                audio_in_filter=krisp_filter,
                audio_out_enabled=True,
            ),
        )

        await run_bot(transport, dialout_settings)

    except Exception as e:
        logger.error(f"Error running bot: {e}")
        raise e



if __name__ == "__main__":
    from pipecat.runner.run import main

    main()
