#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""aws-telephony-bot - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Deepgram on SageMaker (Speech-to-Text)
- Aws_Bedrock (LLM)
- Deepgram on SageMaker (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""


from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.transports.base_transport import BaseTransport
from pipecat.pipeline.pipeline import Pipeline
import os
from pipecat.transports.daily.transport import DailyParams, DailyTransport
from pipecat.pipeline.task import PipelineParams, PipelineTask
from server_utils import AgentRequest, DialoutSettings
from pipecat.services.aws.llm import AWSBedrockLLMService
from pipecat.services.deepgram.sagemaker.stt import DeepgramSageMakerSTTService
from typing import Any, Optional
from pipecat.services.deepgram.sagemaker.tts import DeepgramSageMakerTTSService
from pipecat.services.deepgram.tts import DeepgramTTSService
from pipecat.runner.types import RunnerArguments
from dotenv import load_dotenv
from pipecat.pipeline.runner import PipelineRunner
from loguru import logger
from pipecat.processors.aggregators.llm_response_universal import LLMContextAggregatorPair, LLMUserAggregatorParams
from pipecat.processors.aggregators.llm_response_universal import AssistantTurnStoppedMessage, UserTurnStoppedMessage
from pipecat.processors.logger import FrameLogger
from pipecat.adapters.schemas.function_schema import FunctionSchema
from pipecat.adapters.schemas.tools_schema import ToolsSchema
from pipecat.frames.frames import LLMRunFrame
from pipecat.services.llm_service import FunctionCallParams
from pipecat.audio.vad.silero import SileroVADAnalyzer

load_dotenv(override=True)




class DialoutManager:
    """Manages dialout attempts with retry logic.

    Handles the complexity of initiating outbound calls with automatic retry
    on failure, up to a configurable maximum number of attempts.

    Args:
        transport: The Daily transport instance for making the dialout
        dialout_settings: Settings containing phone number and optional caller ID        max_retries: Maximum number of dialout attempts (default: 5)
    """

    def __init__(
        self,
        transport: BaseTransport,
        dialout_settings: DialoutSettings,
        max_retries: Optional[int] = 5,
    ):
        self._transport = transport
        self._phone_number = dialout_settings.phone_number
        self._max_retries = max_retries
        self._attempt_count = 0
        self._is_successful = False

    async def attempt_dialout(self) -> bool:
        """Attempt to start a dialout call.

        Initiates an outbound call if retry limit hasn't been reached and
        no successful connection has been made yet.

        Returns:
            True if dialout attempt was initiated, False if max retries reached
            or call already successful
        """
        if self._attempt_count >= self._max_retries:
            logger.error(
                f"Maximum retry attempts ({self._max_retries}) reached. Giving up on dialout."
            )
            return False

        if self._is_successful:
            logger.debug("Dialout already successful, skipping attempt")
            return False

        self._attempt_count += 1
        logger.info(
            f"Attempting dialout (attempt {self._attempt_count}/{self._max_retries}) to: {self._phone_number}"
        )

        await self._transport.start_dialout({"phoneNumber": self._phone_number})
        return True

    def mark_successful(self):
        """Mark the dialout as successful to prevent further retry attempts."""
        self._is_successful = True

    def should_retry(self) -> bool:
        """Check if another dialout attempt should be made.

        Returns:
            True if retry limit not reached and call not yet successful
        """
        return self._attempt_count < self._max_retries and not self._is_successful

PROMPT = """
You are a friendly AI assistant calling businesses to verify their addresses. Your responses are being converted to audio, so don't ues any special characters or emoji. Start by confirming you're speaking with someone at Tri-County Plumbing. Once you've confirmed that, ask if they are still located at 123 Main St in Austin, TX. If so, call the confirm_address function. If not, ask them for their new address, then call the update_address function. Once you've confirmed or updated their address, thank them for their time and tell them goodbye. When the user says goodbye, call the end_call function.
"""

async def run_bot(
    transport: BaseTransport, dialout_settings: DialoutSettings
) -> None:
    """Run the voice bot for an outbound call.

    Sets up the bot pipeline with STT, LLM, and TTS services, then initiates
    the dialout and handles the conversation with retry logic.

    Args:
        transport: Daily transport for the call
        dialout_settings: Phone number and optional caller ID for the outbound call
    """
    logger.info("Starting bot")

    # Speech-to-Text service (Deepgram on SageMaker)
    stt = DeepgramSageMakerSTTService(
        endpoint_name=os.getenv("SAGEMAKER_STT_ENDPOINT_NAME"),
        region=os.getenv("AWS_REGION", "us-east-1"),
        settings=DeepgramSageMakerSTTService.Settings(
            model="nova-3",
            language="multi",
            interim_results=True,
            punctuate=True,
            smart_format=False,
        ),
    )

    # Text-to-Speech service (Deepgram on SageMaker)
    tts = DeepgramSageMakerTTSService(
        endpoint_name=os.getenv("SAGEMAKER_TTS_ENDPOINT_NAME"),
        region=os.getenv("AWS_REGION", "us-east-1"),
        settings=DeepgramSageMakerTTSService.Settings(
            voice=os.getenv("DEEPGRAM_VOICE_ID", "aura-2-helena-en"),
        ),
    )

    # Text-to-Speech service (Deepgram direct, because I was having problems with SageMaker)
    # tts = DeepgramTTSService(api_key=os.getenv("DEEPGRAM_API_KEY"), voice="aura-2-andromeda-en")

    # LLM service
    llm = AWSBedrockLLMService(
        aws_region=os.getenv("AWS_REGION"),
        settings=AWSBedrockLLMService.Settings(
            model=os.getenv("AWS_BEDROCK_MODEL"),
            system_instruction=PROMPT,
            temperature=0.8
        ),
    )

    # Function calling tools
    tools = ToolsSchema(standard_tools=[
        FunctionSchema(
            name="verify_address",
            description="Verify that a given address is valid and properly formatted",
            properties={
                "street": {
                    "type": "string",
                    "description": "Street address, e.g. 123 Main St",
                },
                "city": {
                    "type": "string",
                    "description": "City name",
                },
                "state": {
                    "type": "string",
                    "description": "State abbreviation, e.g. CA",
                },
                "zip_code": {
                    "type": "string",
                    "description": "ZIP code",
                },
            },
            required=["street", "city", "state", "zip_code"],
        ),
        FunctionSchema(
            name="update_address",
            description="Update the customer's address on file to a new address",
            properties={
                "street": {
                    "type": "string",
                    "description": "New street address, e.g. 123 Main St",
                },
                "city": {
                    "type": "string",
                    "description": "New city name",
                },
                "state": {
                    "type": "string",
                    "description": "New state abbreviation, e.g. CA",
                },
                "zip_code": {
                    "type": "string",
                    "description": "New ZIP code",
                },
            },
            required=["street", "city", "state", "zip_code"],
        ),
        FunctionSchema(
            name="end_call",
            description="End the current phone call. Use when the user says goodbye or the conversation is complete.",
            properties={},
            required=[],
        ),
    ])

    async def handle_verify_address(params: FunctionCallParams):
        logger.info(f"verify_address called: {params.arguments}")
        # TODO: integrate with a real address verification service
        await params.result_callback({"valid": True, "formatted": (
            f"{params.arguments['street']}, "
            f"{params.arguments['city']}, "
            f"{params.arguments['state']} "
            f"{params.arguments['zip_code']}"
        )})

    async def handle_update_address(params: FunctionCallParams):
        logger.info(f"update_address called: {params.arguments}")
        # TODO: integrate with a real customer database
        await params.result_callback({"success": True, "message": "Address updated successfully."})

    async def handle_end_call(params: FunctionCallParams):
        logger.info("end_call called")
        await params.result_callback({"success": True})
        await task.cancel()

    llm.register_function("verify_address", handle_verify_address)
    llm.register_function("update_address", handle_update_address)
    llm.register_function("end_call", handle_end_call)

    context = LLMContext(tools=tools)
    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(
            vad_analyzer=SileroVADAnalyzer(),
        ),
    )


    
    fl = FrameLogger("out of LLM")


    # Pipeline - assembled from reusable components
    pipeline = Pipeline([
        transport.input(),
        stt,
        user_aggregator,
        llm,
        # fl,
        tts,
        transport.output(),
        assistant_aggregator,
    ])


    task = PipelineTask(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
            audio_in_sample_rate=8000,
            audio_out_sample_rate=8000,
        ),
    )

    # Initialize dialout manager
    dialout_manager = DialoutManager(transport, dialout_settings)

    @transport.event_handler("on_joined")
    async def on_joined(transport, data):
        await dialout_manager.attempt_dialout()

    @transport.event_handler("on_dialout_answered")
    async def on_dialout_answered(transport, data):
        logger.debug(f"Dial-out answered: {data}")
        dialout_manager.mark_successful()

    @transport.event_handler("on_dialout_error")
    async def on_dialout_error(transport, data: Any):
        logger.error(f"Dial-out error, retrying: {data}")

        if dialout_manager.should_retry():
            await dialout_manager.attempt_dialout()
        else:
            logger.error(f"No more retries allowed, stopping bot.")
            await task.cancel()

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info(f"Client disconnected")
        await task.cancel()


    @user_aggregator.event_handler("on_user_turn_stopped")
    async def on_user_turn_stopped(aggregator, strategy, message: UserTurnStoppedMessage):
        timestamp = f"[{message.timestamp}] " if message.timestamp else ""
        line = f"{timestamp}user: {message.content}"
        logger.info(f"Transcript: {line}")

    @assistant_aggregator.event_handler("on_assistant_turn_stopped")
    async def on_assistant_turn_stopped(aggregator, message: AssistantTurnStoppedMessage):
        timestamp = f"[{message.timestamp}] " if message.timestamp else ""
        line = f"{timestamp}assistant: {message.content}"
        logger.info(f"Transcript: {line}")



    runner = PipelineRunner(handle_sigint=False)

    await runner.run(task)


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""
    # Krisp is available when deployed to Pipecat Cloud
    if os.environ.get("ENV") != "local":
        from pipecat.audio.filters.krisp_viva_filter import KrispVivaFilter

        krisp_filter = KrispVivaFilter()
    else:
        krisp_filter = None

    try:
        request = AgentRequest.model_validate(runner_args.body)

        transport = DailyTransport(
            request.room_url,
            request.token,
            "Daily PSTN Bot",
            params=DailyParams(
                api_key=os.getenv("DAILY_API_KEY"),
                audio_in_enabled=True,
                audio_in_filter=krisp_filter,
                audio_out_enabled=True,
            ),
        )

        await run_bot(transport, request.dialout_settings)

    except Exception as e:
        logger.error(f"Error running bot: {e}")
        raise e



if __name__ == "__main__":
    from pipecat.runner.run import main

    main()
